export const colors: { [key: string]: { name: string; colors: string[] } } = {
  primary: {
    name: "Primary",
    colors: [
      "#ddd",
      "#e2e8f0",
      "#e2e8f0",
      "#ddd",
      "#e2e8f0",
      "#e2e8f0",
      "#ddd",
      "#e2e8f0",
      "#e2e8f0",
      "#e2e8f0",
      "#e2e8f0",
    ],
  },
  secondary: {
    name: "Secondary",
    colors: [
      "#ddd",
      "#e2e8f0",
      "#e2e8f0",
      "#ddd",
      "#e2e8f0",
      "#e2e8f0",
      "#ddd",
      "#e2e8f0",
      "#e2e8f0",
      "#e2e8f0",
      "#e2e8f0",
    ],
  },
  tertiary: {
    name: "Tertiary",
    colors: [
      "#ddd",
      "#e2e8f0",
      "#e2e8f0",
      "#ddd",
      "#e2e8f0",
      "#e2e8f0",
      "#ddd",
      "#e2e8f0",
      "#e2e8f0",
      "#e2e8f0",
      "#e2e8f0",
    ],
  },
};
